### ISSUE TITLE
int for types that store article counts is to small, Int64 maybe

### ISSUE THREAD

**Issue by dbeattie71** [keimpema/Usenet#1]
A few,
 public int ArticleCount { get; }
        public int LowWaterMark { get; }
        public int HighWaterMark { get; }

**Comment by keimpema** [comment]
Changed article type from int to long in commit https://github.com/keimpema/Usenet/commit/4c096a268767406a7d2e36622877806509e729cf. Pushed a new version of the package to [nuget](https://www.nuget.org/packages/Usenet/).
