### ISSUE TITLE
Looking for a UUNet Server in C#

### ISSUE THREAD

**Issue by sdfixer** [keimpema/Usenet#17]
I need a UUNet P2P server in Xamarin on Android and iOS, with UUNet data replicated by Bluetooth (see Xamarin Robotics for the code for this).

Do you know of a server project that would be compatible with your library, suitable for this usage?

The need and rationale is that I need to post to the Internet using a chemical indirection (battery, store and forward), to avoid a direct "energy trampoline" by directly interacting with the Internet and connected electrical systems.  (Human Auroa and other aspects of self and soul are too intertwined in the universe and the human invention of real time systems)

If you are interested in either or any discussions please feel free to reach out. This is of a medical nature, and your professional approach to coding and problem solving are wanted.

Thank you, and I really like how you implemented this code.

**Comment by keimpema** [comment]
Sorry. I can't help you with that. Thanks for the compliment though.
