### ISSUE TITLE
articlecount is always 0

### ISSUE THREAD

**Issue by RickySan65** [keimpema/Usenet#3]
article count is always 0 when i try to get groups from a server with listactive.

when i do a listgroup i always get invalid response received

 var lg = client.ListGroup(g.Name);

any hints?

**Comment by keimpema** [comment]
Not all news servers include the article count in the response to the [LISTGROUP](https://tools.ietf.org/html/rfc3977#section-6.1.2) command. You could check the exact response by enabling logging. When using Serilog do something like:

```
// init serilog
Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.RollingFile("log-{Date}.txt")
                .CreateLogger();

var factory = new LoggerFactory();
factory.AddSerilog();

Usenet.LibraryLogging.Factory = factory;

```

For example Extreme Usenet returns the following (no article count and also no low, high or group name):

```
2018-01-04 12:02:34.619 +01:00 [Information] Sending command: "LISTGROUP alt.test.clienttest"
2018-01-04 12:02:34.688 +01:00 [Information] Response received: "211 Article Numbers Follow"
2018-01-04 12:02:34.690 +01:00 [Warning] Invalid response message: "Article Numbers Follow" Expected: {count} {low} {high} {group}

```

You can also use the [GROUP](https://tools.ietf.org/html/rfc3977#section-6.1.1) command (client.Group(g.Name)) to retrieve the article count.

**Comment by RickySan65** [comment]
thanks for the hint :) will keep on digging
