### ISSUE TITLE
Copied code without license notice

### ISSUE THREAD

**Issue by khellang** [keimpema/Usenet#7]
It seems you've taken quite a bit of inspiration and/or copied substantial bits of code from the following of my repositories, without adding proper attribution as required by the MIT license;

 - https://github.com/khellang/yEnc
 - https://github.com/khellang/nntplib.net
 - https://github.com/khellang/Nzb

You even opened a pull request at https://github.com/khellang/yEnc/pull/1, right before this repo was created. I suggest you include proper attribution.

**Comment by leastprivilege** [comment]
..and I would suggest this attribution happens in both the source files, as well as the readme.

**Comment by FransBouma** [comment]
File a DMCA takedown with GitHub. License violations shouldn't be tolerated.

**Comment by keimpema** [comment]
Kristian, your are totally right and I am sorry. It is true that I initially wanted to use all the libraries you mentioned and created. I also wanted to contribute with the PR you mentioned. I guess I got caried away and let my enthousiasm get the best of me and I was too impatient to wait for your response. I was really inspired by your code and although most of mine is build from scratch there is indeed a fair amount in there that is (based on) yours. 

I will add attribution as mentioned in the readme and source files. Will this be sufficient? If not I totally understand and I will take down this repo.

**Comment by khellang** [comment]
> I will add attribution as mentioned in the readme and source files. Will this be sufficient?

No worries! I would appreciate that. Thanks for understanding 👍
