### ISSUE TITLE
Example for retrieving all headers in a group

### ISSUE THREAD

**Issue by keefehiggins** [keimpema/Usenet#9]
Do you have an example of how to retrieve headers in a group preferably by a date range or by specifying a count/range?

I'm looking to pull back items/headers in multiple groups without having to specify a message id.

Thanks!

**Comment by keimpema** [comment]
Maybe [NEWNEWS](https://github.com/keimpema/Usenet/blob/0c0bfaa52f04fbcad6400e9e7b72539c763f79a7/Usenet/Nntp/NntpClient.rfc3977.cs#L332) could be of use to you?

Specs: https://tools.ietf.org/html/rfc3977.html#section-7.4

**Comment by steph4nc** [comment]
The wildmat parameter is not being used in that code, so the command is broken. https://github.com/keimpema/Usenet/blob/master/Usenet/Nntp/NntpClient.rfc3977.cs#L333

**Comment by steph4nc** [comment]
https://github.com/keimpema/Usenet/blob/master/Usenet/Nntp/NntpClient.rfc3977.cs#L333
```csharp
public NntpMultiLineResponse NewNews(string wildmat, NntpDateTime sinceDateTime) =>
            connection.MultiLineCommand($"NEWNEWS {sinceDateTime}", new MultiLineResponseParser(230));
```

Should change to:

```csharp
public NntpMultiLineResponse NewNews(string wildmat, NntpDateTime sinceDateTime) =>
            connection.MultiLineCommand($"NEWNEWS {wildmat} {sinceDateTime}", new MultiLineResponseParser(230));
```

**Comment by keimpema** [comment]
Thanks for letting me know. I will fix this soon.
